### ISSUE TITLE
Enable eth2

### ISSUE THREAD

**Issue by tomlankhorst** [basmeerman/unifi-usg-kpn#12]
I'm new at using Unify products. Is there a way to enable the secondary ethernet interface? 
The configuration file currently states `disabled` at the `eth2` config.

**Comment by tomlankhorst** [comment]
In `config.gateway.json`, `interfaces.ethernet`, I added `eth2`: 

```json
"eth2": {
  "duplex": "auto",
  "speed": "auto"
}
```

**Comment by markimarc** [comment]
Did you also enabled the vlan bridge for VOIP?

**Comment by tomlankhorst** [comment]
@markimarc I'm not using VoIP at home, currently. So I am not sure about this.

**Comment by basmeerman** [comment]
Closed due to inactivity.
