### ISSUE TITLE
Section 4 point 6: executing the ./update_iptv_route.sh

### ISSUE THREAD

**Issue by NewYerk** [basmeerman/unifi-usg-kpn#2]
After step 6 at section 4 I didn’t know I had to execute the file as well. Maybe you could add a step after that with the command to execute the file. So after “ Make the file executable chmod +x /config/scripts/post-config.d/update_iptv_route.sh“  you could add:  ./update_iptv_route.sh. This might be helpful for people that don’t have that much experience with the command prompt, like myself. 
Other than that your tutorial was very helpful, thank you!

**Comment by basmeerman** [comment]
Thanks for the feedback i’ll Add this one!
