### ISSUE TITLE
IPTV Hangs after ~ 24 hours usage

### ISSUE THREAD

**Issue by Veldkornet** [basmeerman/unifi-usg-kpn#20]
I’ve put your config onto a USG 4 Pro, and everything is working perfectly (including addin VLAN7 and a bridge for the phone), however after around 24...36 hours of usage, the IPTV seems to start on all channels, then after a few seconds continues... hangs again...

I checked that IGMP etc are all running, and it all seems good.

Any ideas what to look for?

**Comment by Veldkornet** [comment]
No idea what was wrong, a couple of force provisions and reboots have fixed it.

**Comment by JelleDijkhuizen** [comment]
Do you still have this problem?
I have the same problem and looking for a fix

**Comment by Veldkornet** [comment]
Well, it works usually... But after some time, the USG goes crazy and nothing works, and I need to go into a force provision / reboot frenzy. 

I can’t really say that it’s stable. 
Although it does seem to work better than the KPN modem, so the lesser of two evils I guess. 

Would be nice if we could track down the problem though.

**Comment by JelleDijkhuizen** [comment]
It look like the problems start when the memory is around 40%. Maybe it is because update_iptv_route.sh script that runs every 15 minutes. maybe that needs to change to 1 hour or so
