### ISSUE TITLE
Stuck at adopt

### ISSUE THREAD

**Issue by Marmachine** [basmeerman/unifi-usg-kpn#25]
Hi,

Seems like a great "how to", at least it convinced me of buying a USG-PRO-4.
Anyway, i'm stuck even before step 1...

I guess my problem is that my controller is in a different IP range than the USG at first boot.
Somehow changing the LAN address in the controller doesn't make it appear in the controller either.
So, there seems no way to adopt the thing!?

What did you do? Do you have your controller in the 192.168.1.1 range and did the USG just appear at boot?

**Comment by elfglitch** [comment]
Hi, did you change the config for the USG-PRO-4? The interface names need to be changed. 
The config provided by @basmeerman is based on the USG (the one with three ports).

**Comment by Marmachine** [comment]
Well, i'm not sure what went wrong, it just kept failing, but i think it actually was the user :-)
Fresh attempt today is successfull, have it adopted, thanks anyway.

- Reset the USG-PRO-4
- Connected my laptop to LAN1
- Changed the LAN address for the USG using its config, to one that's currently available and in the same range of the controller
- Disconnected my laptop and connected LAN1 port to the network router
- It appeared in the devices list and so i clicked adopt.

Pretty simple actually! Now, lets play!
Ohh i guess i've found the cause of my trouble earlier; in the controller i see LAN2 port is disabled!
