### ISSUE TITLE
Simplified version wanted (only internet)

### ISSUE THREAD

**Issue by pushnoi** [basmeerman/unifi-usg-kpn#29]
Hi, is it possible you add a simplified config to be used only with Internet? I think the MTU still needs to be adjusted, but no clue as to what I can leave out your current config.

TIA!

**Comment by slootjes** [comment]
You don't need a custom config for only internet. Just go to the controller and set it to DHCP and VLAN 6 :)

**Comment by pushnoi** [comment]
That is what I thought as well. Got loads of disconnects / instability though... might be wrongly set MTU value for PPPoE, but I can't set this through the GUI. Loading this default config did work, but now I have a lot of stuff which I don't need.. Hence my request =)

**Comment by pushnoi** [comment]
Nevermind - I'm having connection issues, also with the original Experiabox.
