### ISSUE TITLE
USG or ER?

### ISSUE THREAD

**Issue by proddy** [basmeerman/unifi-usg-kpn#3]
Thanks for taking the time to write up this project. This is exactly what I was planning to do - swap out my 2xAsus AC86u routers for a Ubiquiti network and replace the KPN Experiabox10. I'm deciding what equipment to buy.

One question regarding your choice of using the USG. If you could build the whole network from scratch again (with unlimited funds :-) ) would you choose the USG or replace with the more powerful EdgeRouters. Same with the EdgeMax switches. The drawback is having one centrally managed UnFi UI and the advantage is not having to install the UnFi controller software somewhere.

**Comment by basmeerman** [comment]
Sry for the long wait. You’ll probably moved on by now, but for future use: I wouldn’t mind using the controller, it’s a docker container that runs wherever. With unlimited funds I would still buy the cheapest solution that works and use the rest of the budget buying the next thing on my bucket list :-)
