### ISSUE TITLE
Change to eth0 description

### ISSUE THREAD

**Issue by eenbrauw** [basmeerman/unifi-usg-kpn#5]
when the USG is updated with firmware version 4.4.21 or above the configuration will cause issues such as red latency and throughput widgets. Furthermore upgrading the controller will show a number or decrypt error when trying to manage the USG.

The solution to this issue is to set the eth0 description to "WAN". 
I might be benificial is you update your JSON script accordingly.

Regards
Eenbrauw

**Comment by slootjes** [comment]
This is addressed here: https://github.com/basmeerman/unifi-usg-kpn/pull/4

**Comment by eenbrauw** [comment]
Goed bezig!

Eenbrauw

**Comment by basmeerman** [comment]
Good busy ;-) thanks pull request is merged.
