### ISSUE TITLE
When using json file usg will not connect to internet anymore

### ISSUE THREAD

**Issue by PA4MIC** [basmeerman/unifi-usg-kpn#6]
U have added/changed the requested information in the json file and uploaded but after provision the usg will not connect anymore to the internet. When i then look in the controller under WAN settings all settings are back to default. When i change them by hand in controller and do provision again settings are back to default. If i then remove the json file an do changes in controller it works again.

I can't find the problem (all are updated to latest versions)

**Comment by PA4MIC** [comment]
Ben er inmiddels achter dat dit stukje er voor zorgt dat de file niet goed gelezen wordt:
"4": {
                                                "address": [
                                                    "dhcp"
                                                ],
                                                "description": "eth0.4 - IPTV",
                                                "dhcp-options": {
                                                        "client-option": [
                                                                "send vendor-class-identifier &quot;IPTV_RG&quot;;",
                                                                "request subnet-mask, routers, rfc3442-classless-static-routes;"
                                                        ],
                                                        "default-route": "no-update",
                                                        "default-route-distance": "210",
                                                        "name-server": "update"
                                                }

Wat kan hier aan fout zijn?

**Comment by basmeerman** [comment]
Pa4mic, what firmware are you running? I’ve issues with the latest firmware on the USG. But not related to the configuration.

**Comment by basmeerman** [comment]
I just compared both parts, you probably have an issue because the quote escape characters are replaced by quotes in the part encapsulating IPTV_RG. Please re-download the file as RAW file from github to ensure you are not have quote encapsulation issues. And let me know if you have any other questions.

**Comment by basmeerman** [comment]
Please let me know if this solved your issue.

**Comment by PA4MIC** [comment]
Both things i know about but it doesn't solve it. The only thing i'm not sure about it when i had downgraded it must work after that. I did the downgrade on controller but i think that i need to do more to work again?
