### ISSUE TITLE
USG loopt/stays offline after provision

### ISSUE THREAD

**Issue by nielsvr** [basmeerman/unifi-usg-kpn#9]
Hi,

The first step of your tutorial works. My USG comes online with internet available. After that, I upload your json file to the controller, update the MAC address and force the USG in provision. After that, the device doesn't come online. If it does, it is voor a minute or 5 without any internet or TV...

If I remove the json, and factory reset the device it comes online again... so I can start again.

Am I missing something?

USG is running 4.4.34.5140612 (up to date)
Controller is at 5.9.29-11384-1 (up to date)

The only thing I see in the 'alerts' of the controller is the following:

USG failed SSH host key verification | 7:15 pm | 12/11/2018 |  

But I think that is unrelated, it happend only after i hard reset the USG and rebooted the rest of the hardware.

Any idea the push my in the right direction?

**Comment by basmeerman** [comment]
I have the same issue, it's unrelated to the config. It has to do something with the firmware versions of the controller and USG. Helpdesk advises to remain on old version until fixed. Once I find time to dive into it I'll let you know.

Have you been able to solve this?
